### ISSUE TITLE
Auto-forward All Headers

### ISSUE THREAD

**Issue by sprjr** [sprjr/json-proxy-middleware#10]
Another use case popped up from @dannycochran in which he depends on all client request headers being automatically forwarded on the proxied request. In my services, most of the time I need to leverage the `headers(){}` option so that I can take the ones I need, add some secret server header keys that I don't ship to the client, and then use those.

It sounds like in his experience, and maybe in most cases?, that just having the client handle this and not having to write `headers: ({ headers }) => headers` is ideal.

@jamesplease you have any objections?

**Comment by jamesplease** [comment]
> Another use case popped up from @dannycochran in which he depends on all client request headers being automatically forwarded on the proxied request.

This should be opt-in imo. Many of our Java backends break if you proxy all of the Meechum headers.

**Comment by sprjr** [comment]
I think what we'll end up with is _not_ automatically forwarding headers. That seems to be the best 'accidental' case coverage. What this means is for now folks will need to make a wrapper to handle their automatic header forwarding, e.g.:


```
export default const wrapper = ({ urlHost, additionalLogMessage }) => jsonProxy({
  urlHost,
  additionLogMessage,
  logger: require('default-logger'),
  headers: (req) => req.headers,
})
```

Or something like that. @dannycochran mentioned perhaps we need a factory to allow for this, so we might be able to add that in the future.
